### ISSUE TITLE
【17.1.10及之前版本】安装在服务器上报错

### ISSUE THREAD

**Issue by gerayking** [wzsjc2020/Minecraft-Comfy-Sky-Mod#2]
```shell
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[02:16:34] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
[02:16:34] [main/INFO]: Loading 43 mods:
        - comfysky 17.1.9
        - fabric-api 0.90.7+1.20.1
           |-- fabric-api-base 0.4.30+7abfd51577
           |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
           |-- fabric-biome-api-v1 13.0.12+215bbe9677
           |-- fabric-block-api-v1 1.0.10+92a0d36777
           |-- fabric-block-view-api-v2 1.0.0+92a0d36777
           |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
           |-- fabric-client-tags-api-v1 1.1.1+97bb207577
           |-- fabric-command-api-v1 1.2.33+f71b366f77
           |-- fabric-command-api-v2 2.2.12+b3afc78b77
           |-- fabric-commands-v0 0.2.50+df3654b377
           |-- fabric-containers-v0 0.1.63+df3654b377
           |-- fabric-content-registries-v0 4.0.10+57aed33f77
           |-- fabric-convention-tags-v1 1.5.4+a1a980da77
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
           |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
           |-- fabric-dimensions-v1 2.1.53+8536527b77
           |-- fabric-entity-events-v1 1.5.22+b3afc78b77
           |-- fabric-events-interaction-v0 0.6.1+e91849a877
           |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
           |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
           |-- fabric-item-api-v1 2.1.27+b3afc78b77
           |-- fabric-item-group-api-v1 4.0.11+d7b148e077
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
           |-- fabric-keybindings-v0 0.2.34+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
           |-- fabric-loot-api-v2 1.2.0+96dfa95977
           |-- fabric-loot-tables-v1 1.1.44+9e7660c677
           |-- fabric-message-api-v1 5.1.8+d7b148e077
           |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
           |-- fabric-model-loading-api-v1 1.0.2+709a987177
           |-- fabric-models-v0 0.4.1+9386d8a777
           |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
           |-- fabric-networking-v0 0.3.50+df3654b377
           |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
           |-- fabric-particles-v1 1.1.1+201a23a077
           |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
           |-- fabric-registry-sync-v0 2.3.2+4df89eb277
           |-- fabric-renderer-api-v1 3.2.0+39a511ba77
           |-- fabric-renderer-indigo 1.5.0+39a511ba77
           |-- fabric-renderer-registries-v1 3.2.45+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
           |-- fabric-rendering-v0 1.1.48+df3654b377
           |-- fabric-rendering-v1 3.0.7+b3afc78b77
           |-- fabric-resource-conditions-api-v1 2.3.6+d7b148e077
           |-- fabric-resource-loader-v0 0.11.9+132c48c177
           |-- fabric-screen-api-v1 2.0.7+b3afc78b77
           |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
           |-- fabric-sound-api-v1 1.0.12+b3afc78b77
           |-- fabric-transfer-api-v1 3.3.2+1bc31aeb77
           \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
        - fabricloader 0.14.24
        - java 17
        - minecraft 1.20.1
[02:16:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/fabric1.20.1/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[02:16:34] [main/INFO]: Compatibility level set to JAVA_17
[02:16:34] [main/WARN]: Error loading class: net/minecraft/class_1092 (java.lang.ClassNotFoundException: net/minecraft/class_1092)
[02:16:34] [main/WARN]: @Mixin target net.minecraft.class_1092 was not found comfysky.mixins.json:BakedModelManagerMixin from mod comfysky
[02:16:44] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'comfysky'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
        at com.wzssoft.comfysky.registry.ComfySkyModMessages.registerS2CPackets(ComfySkyModMessages.java:19) ~[comfysky-1.20.1-17.1.9.jar:?]
        at com.wzssoft.comfysky.ComfySkyMod.onInitialize(ComfySkyMod.java:39) ~[comfysky-1.20.1-17.1.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.wzssoft.comfysky.registry.ComfySkyModMessages.registerS2CPackets(ComfySkyModMessages.java:19) ~[comfysky-1.20.1-17.1.9.jar:?]
        at com.wzssoft.comfysky.ComfySkyMod.onInitialize(ComfySkyMod.java:39) ~[comfysky-1.20.1-17.1.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 7 more
```

**Comment by wzsjc2020** [comment]
感谢报告异常的崩溃问题，经过简单的调查，是由于同步信息S2C注册时应该在客户端注册而非在服务端注册导致的崩溃问题。目前经过简单测试，已经恢复正常。目前我还需要一点时间排除是否所有功能都能在服务端上运行。
服务端崩溃的问题将在下一个版本进行修复（通常是月底），对您游玩造成不便表示抱歉
